CREATE DATABASE BAI14
USE BAI14
CREATE TABLE COSO
(
	MACOSO INT PRIMARY KEY,
	TENCOSO NVARCHAR(50),
)

CREATE TABLE DONVI
(
	MADONVI INT PRIMARY KEY,
	TENDONVI NVARCHAR(50),
	MACOSO INT FOREIGN KEY REFERENCES COSO(MACOSO),
)

CREATE TABLE GV
(
	MAGV INT PRIMARY KEY,
	HOTEN NVARCHAR(50),
	SDT VARCHAR(11),
	GHICHU NVARCHAR(200),
	MADONVI INT FOREIGN KEY REFERENCES DONVI(MADONVI),
)
select * from COSO
